### ISSUE TITLE
master broken

### ISSUE THREAD

**Issue by bpbond** [PNNL-TES/bahn-rs-test#8]
Hi @jinshijian - in 30657693 you removed `SRDB_V4_Fig1.png` which means I now can't knit the document.
<img width="605" alt="Screen Shot 2019-04-04 at 6 47 41 AM" src="https://user-images.githubusercontent.com/1956468/55550285-dbe01880-56a5-11e9-9316-9828ad5aec30.png">

**Comment by jinshijian** [comment]
Hello Ben, can you try it, it should work now. The markdown document is substantially updated, multiple panels are merged together when necessary. And most importantly, Rs_annual are in y-axis now, and the results changed a lot! But it is more interesting, now.
I also replotted the residual vs SPI and PDSI plot, without SPI and PDSI added, the residual show a clear pattern, but when SPI or PDSI added, this pattern disappears!

**Comment by bpbond** [comment]
Ah @jinshijian – I'm still getting errors when I try to build `master`. Could we sit down and look it tomorrow?

**Comment by jinshijian** [comment]
Sure, when works for you? I am available all day. See you tomorrow.

**Comment by jinshijian** [comment]
Hello Ben, can you try now, the error has been debugged and it can be run through at my end. Please let me know if you still got an error. Thanks, Jinshi

**Comment by bpbond** [comment]
Yes, it works now! Thank you. Will open a PR request by our meeting tomorrow.
